submodule-genie --directory $SG_DIRECTORY \
    --remote $SG_REMOTE \
    --branch $SG_BRANCH \
    --fork-owner $SG_FORK_OWNER \
    --fork-repo $SG_FORK_REPO \
    --owner $SG_OWNER \
    --repo $SG_REPO \
    --upstream $SG_UPSTREAM_REMOTE \
    --to-branch $SG_UPSTREAM_BRANCH \
    --submodules $SG_SUBMODULES \
    --token $SG_TOKEN
